blog/app/forms/owncenter.py
from flask_wtf import FlaskForm
from wtforms import Form, StringField, SubmitField, IntegerField, RadioField, PasswordField, SelectField
from wtforms.validators import DataRequired, NumberRange, ValidationError, Length, EqualTo, Email
from flask_wtf.file import FileAllowed, FileRequired, FileField
from .posts import SendPosts
from app.models import User, Category
from app.extensions import file  # 导入文件上传配置对象


# 修改与查看个人信息的表单类
class UserInfo(FlaskForm):
    username = StringField('用户名', render_kw={'readonly': 'true'})
    sex = RadioField(label='性别', choices=[('1', '男'), ('0', '女')], validators=[DataRequired('性别必选')])
    age = IntegerField('年龄', validators=[DataRequired('年龄不能为空'), NumberRange(min=1, max=99, message='年龄在1~99之间')])
    email = StringField('邮箱', render_kw={'readonly': 'true'})
    lastLogin = StringField('上次登录时间', render_kw={'disabled': 'true'})
    register = StringField('注册时间', render_kw={'disabled': 'true'})
    submit = SubmitField('修改')


# 修改与查看个人密码邮箱的表单类
class Change_pwd_email(FlaskForm):
    password = PasswordField(
        '修改密码',
        validators=[DataRequired('密码不能为空...'),
                    Length(min=6, max=12, message='密码在6~12位之间')],
        render_kw={'placeholder': '请输入密码...'}
    )
    new_pwd = PasswordField('确认密码', validators=[DataRequired('确认密码不能为空...')],
                            render_kw={'placeholder': '请输入确认密码...'})

    email = StringField('旧邮箱', validators=[DataRequired('邮箱地址不能为空'), Email(message='请输入正确的邮箱地址')],
                        render_kw={'placeholder': '请输入邮箱'})
    new_email = StringField('新邮箱', validators=[DataRequired('邮箱地址不能为空'), Email(message='请输入正确的邮箱地址')],
                            render_kw={'placeholder': '请输入修改后的邮箱'})

    submit = SubmitField('修改')

    # 验证邮箱是否存在
    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('该邮箱已存在 无需修改')

    # # 验证密码是否正确
    # def validate_password(self, field):
    #     if User.query.filter(
    #             User.check_password(field.data)field.data
    #     ).first():
    #         raise ValidationError('密码错误 请重新输入')


class CategoryForm(SendPosts, Form):
    add_categories = StringField(
        "添加标签",
        validators=[
            DataRequired(u"请输入地址")
        ],
        render_kw={
            "class": "form-control"
        }
    )

    # 验证标签是否存在
    def validate_add_categories(self, field):
        if Category.query.filter_by(name=field.data).first():
            # raise ValidationError('该标签已存在 请重新输入')
            return False
        return True


# # 文件上传类
class Upload(FlaskForm):
    icon = FileField(
        '头像上传',
        validators=[
            FileRequired('您还没有选择上传的头像'),
            FileAllowed(file, message='该文件类型不允许上传')
        ]
    )
    submit = SubmitField('上传')

blog/app/views/owncenter.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, current_app

from app.forms import UserInfo, CategoryForm  # 导入个人信息显示user模型类
from flask_login import current_user, login_required

from app.models import Posts, Category  # 导入博客的模型
from app.forms import SendPosts, Change_pwd_email, Upload  # 导入发表博客模型类 用于编辑博客  # 导入文件上传表单类
from app.extensions import db, file
import os
from PIL import Image

owncenter = Blueprint('owncenter', __name__)


# 查看与修改个人信息
@owncenter.route('/user_info/', methods=['GET', 'POST'])
@login_required
def user_info():
    form = UserInfo()
    if form.validate_on_submit():
        current_user.age = form.age.data
        current_user.sex = int(form.sex.data)
        current_user.save()
    # 表单设置默认值
    form.username.data = current_user.username
    form.age.data = current_user.age
    form.sex.data = str(int(current_user.sex))
    form.email.data = current_user.email
    form.lastLogin.data = current_user.lastLogin
    form.register.data = current_user.registerTime
    return render_template('owncenter/user_info.html', form=form)


# 修改密码
@owncenter.route("/cheage_password")
@login_required
def cheage_password():
    form = Change_pwd_email()
    if form.validate_on_submit():
        pass
    return render_template("owncenter/cheage_pwd_email.html", form=form)


# 修改邮箱
@owncenter.route("/cheage_email")
@login_required
def cheage_email():
    form = Change_pwd_email()
    if form.validate_on_submit():
        pass
    return render_template("owncenter/cheage_pwd_email.html", form=form)


# 博客管理
@owncenter.route('/posts_manager/', methods=['GET', 'POST'])
@login_required
def posts_manager():
    form = CategoryForm()

    # 查看当前用户发表的所有博客  pid为0证明是博客内容而不是评论和回复的内容 state=0是所有人可见  按照时间降序查询
    posts = current_user.posts.filter_by(state=0).order_by(Posts.timestamp.desc())
    return render_template('owncenter/posts_manager.html', posts=posts, form=form)


@owncenter.route('/add_category/', methods=['GET', 'POST'])
@login_required
def add_category():
    form = CategoryForm()
    if not form.validate_add_categories(form.add_categories):
        flash("添加失败,标签已经存在")
        return redirect(url_for("owncenter.posts_manager"))
    if request.method == "POST":
        Category(
            name=form.add_categories.data,
        ).save()
        flash("添加成功")
    else:
        flash("添加失败")
    return redirect(url_for("owncenter.posts_manager"))


@owncenter.route('/del_category/', methods=['GET', 'POST'])
@login_required
def del_category():
    gid = request.form.get("categories", type=int)
    g = Category.query.get_or_404(gid)
    if g:
        g.delete()
        flash("删除成功")
    else:
        flash("删除的标签不存在")
    return redirect(url_for("owncenter.posts_manager"))


# 博客删除
@owncenter.route('/del_posts/<int:pid>/')
@login_required
def del_posts(pid):
    # 查询博客
    p = Posts.query.get(pid)
    # 判断该博客是否存在
    if p:
        # 执行删除
        flash('删除成功')
        p.delete()  # 删除博客内容
    else:
        flash('您要删除的博客不存在')
    return redirect(url_for('owncenter.posts_manager'))


# 博客编辑
@owncenter.route('/edit_posts/<int:pid>/', methods=['GET', 'POST'])
def edit_posts(pid):
    form = SendPosts()  # 实例化表单
    p = Posts.query.get(pid)  # 根据博客id 查询
    if not p:
        flash('该博客不存在')
        return redirect(url_for('owncenter.posts_manager'))
    if form.validate_on_submit():
        p.title = form.title.data  # 进行数据的存储
        p.article = form.article.data
        p.save()
        flash('博客更新成功')
        return redirect(url_for('owncenter.posts_manager'))
    form.title.data = p.title
    form.article.data = p.article
    return render_template('owncenter/edit_posts.html', form=form)


#生成随机图片名称的函数
def new_name(shuffix,length=32):
    import string, random
    myStr = string.ascii_letters + '0123456789'
    newName = ''.join(random.choice(myStr) for i in range(length))
    return newName+"."+shuffix


# 图片缩放处理
def img_zoom(path,prefix="m_", width=200, height=200):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    img.thumbnail((width, height))
    # 拆分传递进来的图片的路径 拆分进行前缀的拼接  /a/b.jpg  /a/s_b.jpg
    pathSplit = os.path.split(path)
    # 拼接好前缀 进行重新拼接成一个新的path
    path = os.path.join(pathSplit[0], prefix+pathSplit[1])
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


# 头像上传
@owncenter.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = Upload()
    # 验证数据
    if form.validate_on_submit():
        icon = request.files.get('icon')  # 获取上传对象
        suffix = icon.filename.split('.')[-1]  # 获取后缀
        newName = new_name(suffix)
        # 保存图片 以新名称
        file.save(icon, name=newName)
        delPath = current_app.config['UPLOADED_PHOTOS_DEST']
        # 删除之前上传过的图片
        if current_user.icon != 'default.png':  # 如果不等于 证明之前有上传过头像 否则就是没有上传过新头像
            os.remove(os.path.join(delPath, current_user.icon))
            os.remove(os.path.join(delPath, "m_"+current_user.icon))
        with db.auto_commit():
            current_user.icon = newName  # 更改当前对象的图片名称
            db.session.add(current_user)  # 更新到数据库中
        # 拼接图片路径
        path = os.path.join(delPath, newName)
        # 进行头像的缩放
        img_zoom(path)
    return render_template('owncenter/upload.html', form=form)


# 收藏管理
@owncenter.route('/my_favorite/')
@login_required
def my_favorite():
    # 查出当前用户的所有收藏的博客
    posts = current_user.favorites.all()
    return render_template('owncenter/my_favorite.html', posts=posts)


# 取消收藏
@owncenter.route('/del_favorites/<int:pid>/')
@login_required
def del_favorites(pid):
    # 判断是否收藏了
    if current_user.is_favorite(pid):
        # 调用取消收藏
        current_user.delete_favorite(pid)
    flash('取消收藏成功')
    return redirect(url_for('owncenter.my_favorite'))

blog/app/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request, jsonify
from app.forms import SendPosts, Comment  # 导入发表博客与评论回复表单类
from app.models import Posts, Category, Comment as Comments  # 导入博客模型类
from flask_login import login_required, current_user
from sqlalchemy import or_  # 导入或查询

posts = Blueprint('posts', __name__)


# 发表博客
@posts.route('/send_posts/', methods=['GET', 'POST'])
@login_required
def send_posts():
    form = SendPosts()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后在发表')
    elif form.validate_on_submit():
        # 保存发表博客的数据
        Posts(
            title=form.title.data,
            article=form.article.data,
            user=current_user,
            category_id=form.categories.data
        ).save()
        flash('博客发表成功')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form)



# 博客搜索
@posts.route('/search/', methods=['GET', 'POST'])
def search():
    try:
        page = request.args.get('page', 1, type=int)
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
        print(keyword)
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0并且所有人可见的博客  pid不为0 证明是评论和回复的内容  按照时间的降序显示
    pagination = Posts.query.filter(
        or_(
            Posts.title.ilike("%" + keyword + "%"),
            Posts.article.ilike("%" + keyword + "%")
        ),
        Posts.state == 0
    ).order_by(
        Posts.timestamp.desc()
    ).paginate(page, current_app.config['PAGE_NUM'])
    data = pagination.items  # 获取page页面的数据
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword)


# 博客详情
@posts.route('/posts_detail/')
def posts_detail():
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    pid = request.args.get("pid")
    page = request.args.get("page", 1, type=int)
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复 按照博客内容和回复在一起的排序顺序  过滤条件为博客的path宏包含博客id 的 这样就将博客的内容过滤了出去  只查询评论和回复的内容
    pagedata = Comments.query.filter(
        Comments.post_id == p.id
    ).order_by(Comments.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'])
    return render_template('posts/posts_detail.html', posts=p, form=form, comment=pagedata)


# 评论
@posts.route('/comment/', methods=["GET", "POST"])
@login_required
def comment():
    form = Comment()
    if form.validate_on_submit():
        page = request.form.get("page", 1, type=int)
        pid = request.form.get("pid", type=int)
        count = request.form.get("content")
        uid = current_user.id
        Comments(
            count=count,
            post_id=pid,
            user_id=uid
        ).save()
    return redirect(url_for("posts.posts_detail", pid=pid, page=page))


# 回复
@posts.route('/reply/', methods=['GET', 'POST'])
@login_required
def reply():
    page = request.form.get("page", 1, type=int)
    form = Comment()
    if form.validate_on_submit():
        pid = request.form.get('pid', type=int)
        rid = request.form.get('rid', type=int)
        count = request.form.get("content")
        uid = current_user.id
        Comments(
            count=count,
            post_id=pid,
            user_id=uid,
            replied_id=rid,
        ).save()
    return redirect(url_for('posts.posts_detail', pid=pid, page=page))


# 处理博客收藏与取消收藏的操作
@posts.route('/do_favorite/')
def do_favorite():
    try:
        # 获取ajax传递过来的pid
        pid = request.args.get('pid', type=int)
        # 判断是否收藏了
        if current_user.is_favorite(pid):
            # 调用取消收藏
            current_user.delete_favorite(pid)
        else:
            # 调用执行收藏
            current_user.add_favorite(pid)
        return jsonify({'res': 200})
    except:
        return jsonify({'res': 500})

blog/app/templates/owncenter/cheage_pwd_email.html
{% extends 'common/base.html' %}
{% block title %}
    修改博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block scripts %}
    {{ super() }}
    <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
{% endblock %}
{% block page_content %}
    <h2 class="page-header">修改密码&邮箱</h2>
    <form action="" method="post">
        {{ form.password.label() }}
        {{ form.password(class='form-control') }}
        {% for err in form.password.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <br/>
        {{ form.new_pwd.label() }}
        {{ form.new_pwd(class='form-control') }}
        {% for err in form.new_pwd.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}

        <br>
        {{ form.email.label(style='font-size:16px;') }}
        {{ form.email(class='form-control') }}
        {% for err in form.email.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        {{ form.new_email.label(style='font-size:16px;') }}
        {{ form.new_email(class='form-control') }}
        {% for err in form.new_email.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">更新</button>
    </form>
{% endblock %}

{% block page_right %}
{% endblock %}

blog/app/templates/owncenter/edit_posts.html
{% extends 'common/base.html' %}
{% block title %}
    修改博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block scripts %}
    {{ super() }}
    <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
{% endblock %}
{% block page_content %}
    <h2 class="page-header">更新博客</h2>
    <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.title.label() }}
        {{ form.title(class='form-control') }}
        {% for err in form.title.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br/>
        {{ form.categories.label() }}
        {{ form.categories(class='form-control') }}
        {% for err in form.categories.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}

        <br>
        {{ form.article.label(style='font-size:16px;') }}
        {{ form.article(class="ckeditor") }}
        {% for err in form.article.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">更新</button>
    </form>
{% endblock %}

{% block page_right %}
{% endblock %}

blog/app/templates/owncenter/my_favorite.html
{% extends 'common/base.html' %}
{% block title %}
    收藏管理
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <style>
    td a{
        color:#000000;
    }
    </style>
{% endblock %}
{% block page_content %}
    <h2 class="page-header">收藏管理</h2>
    <form class="form-inline definewidth m20" action="index.html" method="get">
        博客名称：
        <input type="text" name="username" id="username" class="abc input-default" placeholder="" value="">&nbsp;&nbsp;
        <button type="submit" class="btn btn-primary">查询</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-success" id="addnew" onclick="window.location.href={{ url_for('posts.send_posts') }}">新增博客</button>
    </form>
    <table class="table table-bordered table-hover definewidth m10">
        <thead>
        <tr>
            <th>id</th>
            <th>标题</th>
            <th>博客内容</th>
            <th>浏览量</th>
            <th>是否所有人可见</th>
            <th>发表时间</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for row in posts %}
        <tr>
            <td>{{ loop.revindex }}</td>
            <td>{{ row.title }}</td>
            <td>{{ row.article|striptags|showEllipsis(20) }}</td>
            <td>{{ row.visit }}次</td>
            <td>
                {% if row.state %}
                    仅自己可见
                {% else %}
                    所有人可见
                {% endif %}
            </td>
            <td>{{ moment(row.timestamp).format('YYYY-MM-DD H:m:s') }}</td>
            <td>
                <a href="{{ url_for('owncenter.del_favorites',pid=row.id) }}">取消收藏</a> |
                <a href="{{ url_for('posts.posts_detail',pid=row.id) }}" target="_blank">查看</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    </div>
{% endblock %}
{% block page_right %}
{% endblock %}

blog/app/templates/owncenter/posts_manager.html
{% extends 'common/base.html' %}
{% block title %}
    博客管理
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static',filename='css/style.css') }}">
    <style>
    td a{
        color: black;
    }
    </style>
{% endblock %}
{% block page_content %}
    <p>
    <h2 class="page-header">博客管理</h2>
    <form class="form-inline definewidth m20" action="#" method="get">
        博客名称：
        <input type="text" name="username" id="username" class="abc input-default" placeholder="" value="">&nbsp;&nbsp;
        <button type="submit" class="btn btn-primary">查询</button>
        &nbsp;&nbsp;
        <button type="button" class="btn btn-success" id="addnew" onclick="window.location.href={{ url_for('posts.send_posts') }}">新增博客</button>
    </form>
    <table class="table table-bordered table-hover definewidth m10">
        <thead>
        <tr>
            <th>id</th>
            <th>标题</th>
            <th>博客内容</th>
            <th>浏览量</th>
            <th>是否所有人可见</th>
            <th>发表时间</th>
            <th>操作</th>
        </tr>
        </thead>
        {% for row in posts %}
        <tr>
            <td>{{ loop.revindex }}</td>
            <td>{{ row.title }}</td>
            <td>{{ row.article|striptags|showEllipsis(20) }}</td>
            <td>{{ row.visit }}次</td>
            <td>
                {% if row.state %}
                    仅自己课件
                {% else %}
                    所有人可见
                {% endif %}
            </td>
            <td>{{ moment(row.timestamp).format('YYYY-MM-DD H:m:s') }}</td>
            <td>
                <a href="{{ url_for('owncenter.edit_posts',pid=row.id) }}" target="_blank">编辑</a> |
                <a href="{{ url_for('owncenter.del_posts',pid=row.id) }}">删除</a> |
                <a href="{{ url_for('posts.posts_detail',pid=row.id) }}" target="_blank">查看</a>
            </td>
        </tr>
        {% endfor %}

    </table>
    </p>
    <br>
    <p>
    <form action="{{ url_for("owncenter.add_category") }}" method="post">
        {{ form.csrf_token }}
        {{ form.add_categories.label() }}
        {{ form.add_categories(class='form-control') }}
        {% for err in form.add_categories.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">添加</button>
    </form>
    </p>
       <br>
    <p>
    <form action="{{ url_for("owncenter.del_category") }}" method="post">
        {{ form.csrf_token }}

        {{ form.categories.label() }}
        {{ form.categories(class='form-control') }}
        {% for err in form.categories.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br/>
        <button type="submit" class="btn btn-success">删除</button>
    </form>
    </p>
{% endblock %}
{% block page_right %}
{% endblock %}

blog/app/templates/owncenter/upload.html
{% extends 'common/base.html' %}
{% block title %}
    头像上传
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block page_content %}
<h2 class="page-header">头像上传</h2>
    <img src="{{ url_for('static',filename='upload/m_'+current_user.icon) }}" alt="" width="200" style="border-radius:10px;">
    <hr>
    {{ quick_form(form) }}
{% endblock %}
{% block page_right %}
{% endblock %}

blog/app/templates/owncenter/user_info.html
{% extends 'common/base.html' %}
{% block title %}
    查看个人信息
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block page_content %}
    <h2 class="page-header">查看与修改个人信息</h2>
    <div class="row">
  <div class="col-md-8">{{ quick_form(form) }}</div>
  <div class="col-md-4"></div>
</div>
{% endblock %}
{% block page_right %}
{% endblock %}