moves/APP/home/forms.py
from wtforms import StringField, SubmitField,PasswordField
from wtforms.validators import DataRequired,ValidationError,Email,Regexp
from flask_wtf import FlaskForm


# 注册表单
from APP import User


class RegisterForm(FlaskForm):
    username = StringField(
        label="昵称",
        validators=[
            DataRequired("请输入昵称")
        ],
        description="昵称",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "昵称"
        }
    )
    email = StringField(
        label="邮箱",
        validators=[
            DataRequired("请输入邮箱"),
            Email("邮箱格式不正确")
        ],
        description="邮箱",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "邮箱"
        }
    )
    phone = StringField(
        label="手机",
        validators=[
            DataRequired("请输入手机号"),
            Regexp("1[34578]\\d[10]",message="手机格式不正确")

        ],
        description="手机",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "手机"
        }
    )
    password = PasswordField(
        label="密码",
        validators=[
            DataRequired("请输入密码")
        ],
        description="密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "密码"
        }
    )
    rpassword = PasswordField(
        label="确认密码",
        validators=[
            DataRequired("请再次输入密码"),
            #EqualTo(password,message="俩次密码不一致！")
        ],
        description="确认密码",
        render_kw={
            "class": "form-control input-lg",
            "placeholder": "确认密码"
        }
    )
    submit = SubmitField(
        "注册",
        render_kw={
            "class": "btn btn-lg btn-success btn-block"
        }
    )

    def validata_name(self,field):
        name=field.data
        sum=User.query.filter_by(username=name).count()
        if sum==1:
            raise ValidationError("用户名已存在")

    def validata_email(self,field):
        email=field.data
        sum=User.query.filter_by(emial=email).count()
        if sum==1:
            raise ValidationError("用户名已存在")

    def validata_name(self,field):
        phone=field.data
        sum=User.query.filter_by(phone=phone).count()
        if sum==1:
            raise ValidationError("用户名已存在")

moves/APP/home/__init__.py
from flask import Blueprint

home=Blueprint("home",__name__)

from . import views

moves/APP/home/views.py
import uuid

from APP import User, db, Userlog, Movie, Prevaew, Tag, Comment, Moviecol
from APP.home.forms import RegisterForm
from . import home
from flask import render_template, url_for, redirect, flash, request, session
from functools import wraps


def admin_login_req(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not session.get("username"):
            return redirect(url_for("home.logins", next=request.url))
        return f(*args, **kwargs)

    return decorated_function



@home.route('/home/')
def homes():
    return render_template("home/home.html")


# 登陆
@home.route('/login/', methods=["GET", "POST"])
def logins():
    if request.method == 'GET':
        return render_template("home/login.html")
    if request.method == "POST":
        password = request.form.get("password")
        contact = request.form.get("contact")
        sum = User.query.filter(User.username == contact).count()
        if sum == 1:
            users = User.query.filter(User.username == contact).first()
            print(users)
            if users.username == contact and users.password == password:
                session["username"] = contact
                session["user_id"] = users.id
                # flash("登陆成功", "ok")
                userlog = Userlog(
                    user_id=session.get("user_id"),
                    ip=request.remote_addr
                )
                db.session.add(userlog)
                db.session.commit()
                return redirect(url_for("home.user"))
            else:
                flash("用户名或者密码不正确", "err")
        else:
            flash("用户不存在", "err")
        print(password)
        print(contact)

    return render_template("home/login.html")


# 注销
@home.route('/loginout/')
@admin_login_req
def loginout():
    if session.get("username"):
        session.pop("username")
        session.pop("user_id")
        flash("您已成功退出，请重新登陆", "ok")
    else:
        flash("您还没有登陆，请登陆", "err")
        redirect(url_for("home.logins"))
    return redirect(url_for("home.logins"))


# 注册
@home.route('/regist/', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    print(form.validate_on_submit())
    if form.validate_on_submit():
        data = form.data
        sum = User.query.filter(User.username == data.get("username")).count()
        sum2 = User.query.filter(User.phone == data.get("phone")).count()
        sum3 = User.query.filter(User.emial == data.get("email")).count()

        if not (sum == 1) and not (sum2 == 1) and not (sum3 == 1):
            if data.get("password") == data.get("rpassword"):
                user = User(
                    username=data.get("username"),
                    password=data.get("password"),
                    emial=data.get("email"),
                    phone=data.get("phone"),
                    uuid=uuid.uuid4().hex
                )
                db.session.add(user)
                db.session.commit()
                flash("注册成功", "ok")
                return redirect(url_for("home.logins"))
            else:
                flash("俩次密码不一致", "err")
        else:
            flash("表单中有重复项目", "err")
    return render_template("home/regist.html", form=form)


# 用户
@home.route('/user/', methods=["GET", "POST"])
@admin_login_req
def user():
    user_id = session.get("user_id")
    user = User.query.filter_by(id=user_id).first()
    if request.method == "GET":
        return render_template("home/user.html", user=user)
    if request.method == "POST":
        username = request.form.get("name")
        emial = request.form.get("email")
        phone = request.form.get("phone")
        if user and emial and phone:
            user.username = username
            user.emial = emial
            user.phone = phone
            user.face = request.form.get("face")
            user.info = request.form.get("info")
            db.session.add(user)
            db.session.commit()
            flash("修改成功", "ok")
        else:
            flash("用户名，邮箱，电话不可以为空", "err")
    return render_template("home/user.html", user=user)


# 密码
@home.route('/pwd/', methods=["GET", "POST"])
@admin_login_req
def pwd():
    if request.method == "GET":
        return render_template("home/pwd.html")
    if request.method == "POST":
        logings_user = User.query.filter_by(id=session.get("user_id")).first()

        if request.form.get("oldpwd") == logings_user.password:
            if request.form.get("newpwd"):
                logings_user.password = request.form.get("newpwd")
                db.session.add(logings_user)
                db.session.commit()
                flash("修改成功", "ok")
            else:
                flash("密码不能为空", "err")
        else:
            flash("旧密码错误", "err")

    return render_template("home/pwd.html")


# 评论记录
@home.route('/comments/<int:page>/')
@admin_login_req
def comments(page=None):
    if page == None:
        page = 1
    page_data = Comment.query.filter(Comment.user_id == session.get("user_id")).paginate(page=page, per_page=5)
    return render_template("home/comments.html", page_data=page_data)


# 登陆日志
@home.route('/loginlog/<int:page>')
@admin_login_req
def loginlog(page=None):
    if page == None:
        page = 1
    page_data = Userlog.query.join(
        User
    ).filter(
        User.id == session.get("user_id"),
        Userlog.user_id == User.id
    ).paginate(page=page, per_page=5)
    return render_template("home/loginlog.html", page_data=page_data)


# 评论记录
# 电影添加
@home.route('/moviecol/add/')
@admin_login_req
def moviecol_add():
    uid = request.args.get("uid", "")
    mid = request.args.get("mid", "")
    moviecol = Moviecol.query.filter(Moviecol.movie_id == mid, Moviecol.user_id == uid).count()
    if moviecol == 1:
        data = dict(ok=0)
    if moviecol == 0:
        moviecol = Moviecol(
            movie_id=mid,
            user_id=uid,
        )
        db.session.add(moviecol)
        db.session.commit()
        data = dict(ok=1)

    import json
    return json.dumps(data)


# 电影收藏
@home.route('/moviecol/<int:page>/')
@admin_login_req
def moviecol(page=None):
    if page == None:
        page = 1

    page_data = Moviecol.query.filter(Moviecol.user_id == session.get("user_id")).paginate(page=page, per_page=5)

    return render_template("home/moviecol.html", page_data=page_data)


@home.route("/")
def indexs():
    return redirect(url_for("home.index", page=1))


# 主页
@home.route('/<int:page>')
def index(page=None):
    if page == None:
        page = 1
    tags = Tag.query.all()
    page_data = Movie.query
    tid = request.args.get("tid", 0)

    if int(tid) != 0:
        page_data = page_data.filter(Movie.tag_id == tid)

    star = request.args.get("star", 0)
    if int(star) != 0:
        page_data = page_data.filter(Movie.star == star)

    time = request.args.get("time", 0)
    if int(time) != 0:
        if int(time) == 1:
            page_data = page_data.order_by(Movie.add_time.desc())
        elif int(time) == 2:
            page_data = page_data.order_by(Movie.add_time.asc())

    pm = request.args.get("pm", 0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data = page_data.order_by(Movie.playnum.desc())
        elif int(pm) == 2:
            page_data = page_data.order_by(Movie.playnum.asc())

    cm = request.args.get("cm", 0)
    if int(cm) != 0:
        if int(cm) == 1:
            page_data = page_data.order_by(Movie.commentnum.desc())
        elif int(cm) == 2:
            page_data = page_data.order_by(Movie.commentnum.asc())

    page_data = page_data.paginate(page=page, per_page=1)

    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )
    print(page_data.items)
    return render_template("home/index.html", tags=tags, p=p, page_data=page_data)


# 轮播图
@home.route('/anamation/')
def anamation():
    data = Prevaew.query.all()
    # print(page_data)
    print()
    return render_template("home/anamation.html", data=data)


# 搜索
@home.route('/search/<int:page>/')
def search(page=None):
    if page == None:
        page = 1
    key = request.args.get("key", "")
    page_data = Movie.query.filter(
        Movie.title.ilike("%" + key + "%")
    ).order_by(
        Movie.add_time.desc()
    ).paginate(page=page, per_page=1)
    num = len(page_data.items)
    print(num)
    page_data.key=key

    return render_template("home/search.html", key=key, page_data=page_data, num=num)


# 评论页面
@home.route('/play/<int:id>/<int:page>/', methods=["GET", "POST"])
def play(id=None, page=None):
    if page == None:
        page = 1
    page_data = Comment.query.filter(Comment.movie_id == id).order_by(Comment.add_time.desc()).paginate(page=page,
                                                                                                        per_page=10)
    print(page_data.items)
    num = len(Comment.query.all())
    movie = Movie.query.get_or_404(id)

    if request.method == "GET":
        movie.playnum = movie.playnum + 1
        db.session.add(movie)
        db.session.commit()
        return render_template("home/play.html", movie=movie, page_data=page_data)
    if request.method == "POST":

        if request.form.get("comment") and session.get("username"):
            comment = Comment(
                content=request.form.get("comment"),
                movie_id=id,
                user_id=session.get("user_id")
            )
            db.session.add(comment)
            db.session.commit()
            movie.commentnum = movie.commentnum + 1
            db.session.add(movie)
            db.session.commit()
        else:
            flash("请登陆以后再来评论", "err")
        page_data = Comment.query.filter(Comment.movie_id == id).order_by(Comment.add_time.desc()).paginate(page=page,
                                                                                                            per_page=10)
        print(page_data.items)

moves/APP/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for("static",filename="base/images/logo.png") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/bootstrap.min.css")}}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/bootstrap-movie.css")}}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/animate.css")}}">
    <style>
        .navbar-brand > img {
            display: inline;
        }
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block Style %}

    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for("home.index",page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for("static",filename="base/images/logo.png")}}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search_click" ><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for("home.homes") }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.logins") }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.register") }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.loginout") }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href={{ url_for("home.user") }}><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->

<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}

    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for("static",filename="base/js/jquery.min.js")}}"></script>
<script src="{{ url_for("static",filename="base/js/bootstrap.min.js")}}"></script>
<script src="{{ url_for("static",filename="base/js/jquery.singlePageNav.min.js")}}"></script>
<script src="{{ url_for("static",filename="base/js/wow.min.js")}}"></script>
<script src="{{ url_for("static",filename="lazyload/jquery.lazyload.min.js")}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#search_click").click(function () {
            var key=$("#key_movie").val();
            location.href="{{ url_for("home.search",page=1) }}?key="+key;
        });
    });

</script>
{% block js %}

{% endblock %}
</body>
</html>

moves/APP/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for("static",filename="base/images/logo.png") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/bootstrap.min.css") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/bootstrap-movie.css") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/animate.css") }}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

        .media {
            padding: 3px;
            border: 1px solid #ccc
        }
    </style>
    {% block Style %}

    {% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for("home.index",page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for("static",filename="base/images/logo.png") }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！" id="key_movie">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="search_click"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for("home.homes",page=1) }}"><span
                            class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.logins") }}"><span
                            class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.register") }}"><span
                            class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for("home.loginout") }}"><span
                            class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href={{ url_for("home.user") }}><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->

<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}

    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2017&nbsp;flaskmovie.imooc.com&nbsp;京ICP备 13046642号-2
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for("static",filename="base/js/jquery.min.js") }}"></script>
<script src="{{ url_for("static",filename="base/js/bootstrap.min.js") }}"></script>
<script src="{{ url_for("static",filename="base/js/jquery.singlePageNav.min.js") }}"></script>
<script src="{{ url_for("static",filename="base/js/wow.min.js") }}"></script>
<script src="{{ url_for("static",filename="lazyload/jquery.lazyload.min.js") }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $("#search_click").click(function () {
            var key = $("#key_movie").val();
            location.href = "{{ url_for("home.search",page=1) }}?key=" + key;
        });
    });

</script>
{% block js %}

{% endblock %}
</body>
</html>

moves/APP/templates/home/menu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for("static",filename="base/images/logo.png") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/bootstrap.min.css")}}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/bootstrap-movie.css")}}">
    <link rel="stylesheet" href="{{ url_for("static",filename="base/css/animate.css")}}">
    <style>
        .navbar-brand > img {
            display: inline;
        }

    </style>
    <style>
        .media {
            padding: 3px;
            border: 1px solid #ccc
        }

    </style>
</head>
<body>
<div class="col-md-3">
        <div class="list-group">
            <a id="m-1" href="{{ url_for("home.user") }}" class="list-group-item">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id="m-2" href="{{ url_for("home.pwd")}}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id="m-3" href="{{ url_for("home.comments",page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a id="m-4" href="{{ url_for("home.loginlog",page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a id="m-5" href="{{ url_for("home.moviecol",id=session["user_id"],page=1)}}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏电影
            </a>
        </div>
    </div>
<script src="{{ url_for("static",filename="base/js/jquery.min.js")}}"></script>
<script src="{{ url_for("static",filename="base/js/bootstrap.min.js")}}"></script>
<script src="{{ url_for("static",filename="base/js/jquery.singlePageNav.min.js")}}"></script>
<script src="{{ url_for("static",filename="base/js/wow.min.js")}}"></script>
<script src="{{ url_for("static",filename="lazyload/jquery.lazyload.min.js")}}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function () {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function () {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
</body>
</html>

moves/APP/templates/home/moviecol.html
{% extends "home/home.html" %}

{% include "home/menu.html" %}
{% import "home/page_list.html" as pp %}
{% block Style %}
    <style>
        .col-lg-1, .col-lg-10, .col-lg-11, .col-lg-12, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-md-1, .col-md-10, .col-md-11, .col-md-12, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-sm-1, .col-sm-10, .col-sm-11, .col-sm-12, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-xs-1, .col-xs-10, .col-xs-11, .col-xs-12, .col-xs-2, .col-xs-3, .col-xs-4, .col-xs-5, .col-xs-6, .col-xs-7, .col-xs-8, .col-xs-9 {
            padding-right: 3px;
            padding-left: 3px;
        }
    </style>
{% endblock %}


{% block content %}
        <div class="col-md-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-map-marker"></span>&nbsp;收藏电影</h3>
                </div>
                <div class="panel-body">
                    <div class="col-md-12">

                        {% for foo in page_data.items %}
                        <div class="media">
                            <div class="media-left">
                                <a href="{{ url_for("home.play",page=1,id=foo.movie.id) }}">
                                    <img class="media-object" src="holder.js/131x83" alt="环太平洋">
                                </a>
                            </div>
                            <div class="media-body">
                                <h4 class="media-heading">{{ foo.movie.title }}<a href="{{ url_for("home.play",page=1,id=foo.movie.id) }}"
                                                                 class="label label-primary pull-right"><span
                                        class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                                {{ foo.movie.info }}
                            </div>
                        </div>
                        {% endfor %}



                    </div>
                    <div class="col-md-12 text-center" style="margin-top:6px;">
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                {{ pp.render_page(page_data,"home.moviecol") }}
                               {# <li>
                                    <a href="#" aria-label="First">
                                        <span aria-hidden="true">首页</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" aria-label="Previous">
                                        <span aria-hidden="true">上一页</span>
                                    </a>
                                </li>
                                <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                                <li>
                                    <a href="#" aria-label="Next">
                                        <span aria-hidden="true">下一页</span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" aria-label="Last">
                                        <span aria-hidden="true">尾页</span>
                                    </a>
                                </li>#}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function () {
           $("#m-5").addClass("active");
        });
    </script>
{% endblock %}

moves/APP/templates/home/page_list.html
{% macro render_page(page_data,url) %}
    {% if page_data %}

        <li><a href="{{ url_for(url,page=1) }}" aria-label="First"><span aria-hidden="true">首页</span></a></li>
        {% if page_data.has_prev %}
            <li><a href="{{ url_for(url,page=page_data.prev_num) }}" aria-label="Previous"><span
                    aria-hidden="true">上一页</span></a></li>
        {% else %}
            <li><a class="disabled" aria-label="Previous"><span aria-hidden="true">上一页</span></a></li>
        {% endif %}

        {% for foo in page_data.iter_pages() %}
            {% if foo %}
            {% if foo==page_data.page %}
                <li><a href="#" class="active">{{ foo }}</a></li>
            {% else %}
                <li><a href="{{ url_for(url,page=foo) }}" class="active">{{ foo }}</a></li>
            {% endif %}
            {% endif %}
        {% endfor %}

        {% if page_data.has_next %}
            <li><a href="{{ url_for(url,page=page_data.next_num) }}" aria-label="Next"><span
                    aria-hidden="true">下一页</span></a></li>
        {% else %}
            <li><a class="disabled" href="#" aria-label="Next"><span aria-hidden="true">下一页</span></a></li>
        {% endif %}
        <li><a href="{{ url_for(url,page=page_data.pages) }}" aria-label="Last"><span aria-hidden="true">尾页</span></a></li>
    {% endif %}
{% endmacro %}