blog/app/models/posts.py
from flask import current_app

from app.extensions import db
from .db_base import DB_Base
from datetime import datetime


class Category(db.Model, DB_Base):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), unique=True)
    # 设置与post的双向关系
    # posts = db.relationship('Post',secondary="tags_posts", back_populates='categories')
    posts = db.relationship('Posts', back_populates='categories')


# 博客模型
class Posts(db.Model, DB_Base):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(20), index=True)  # 博客标题
    article = db.Column(db.Text)  # 博客的内容
    visit = db.Column(db.Integer, default=0)  # 访问量
    state = db.Column(db.Integer, default=0)  # 是否所有人可见
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)  # 发表时间
    # 设置一对多外键
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    # 设置与comment的双向关系
    comments = db.relationship('Comment', back_populates='posts', cascade='all, delete-orphan')

    # 设置与category的双向关系
    # categories= db.relationship('Post', secondary="tags_posts", back_populates='posts')
    categories = db.relationship('Category', back_populates='posts')


class Comment(db.Model, DB_Base):
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True)
    count = db.Column(db.Text)
    from_admin = db.Column(db.Boolean, default=False)
    timestamp = db.Column(db.DateTime, index=True)

    user_id = db.Column(db.Integer, db.ForeignKey("user.id"))
    user = db.relationship('User', back_populates='comments')

    # 外键，指向文章表的ｉｄ与文章构成一对多关系（一个文章有多个评论）
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    # 与文章的双向级联关系
    posts = db.relationship('Posts', back_populates='comments')

    # 设置回复，指向自己的ｉｄ（邻接列表）与评论构成一对多关系（一个评论有多个回复）
    replied_id = db.Column(db.Integer, db.ForeignKey('comment.id'))

    # 评论的回复：级联删除，当评论被删除的时候，所有的回复将被删除（级联删除设置在“多”这一侧）
    replies = db.relationship('Comment', back_populates='replied', cascade='all, delete-orphan')
    # 父对象，也就是被评论的那个（相当于一篇文章）标量关系
    replied = db.relationship('Comment', back_populates='replies', remote_side=[id])

blog/app/forms/posts.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import Length, DataRequired, ValidationError
from app.models import Category


# 发表博客的表单类
class SendPosts(FlaskForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.categories.choices = [(v.id, v.name) for v in Category.query.all()]

    title = StringField(
        '标题',
        validators=[
            DataRequired('标题内容不能为空'),
            Length(min=3, max=20, message='标题内容在3~20字之间')
        ],
        render_kw={"placeholder": '请输入标题'}
    )
    article = TextAreaField(
        '博客内容'
        , validators=[
            DataRequired('博客内容不能为空'),
            Length(min=20, max=2000, message='博客内容在20~1000字之间')
        ],
        render_kw={"placeholder": '请输入博客内容'}
    )
    categories = SelectField(
        "标签列表",
        validators=[
            DataRequired(u"请选择一个标签")
        ],
        description=u"标签列表列表",
        coerce=int,
        choices="",
        render_kw={
            "class": "form-control"
        }
    )
    submit = SubmitField('发表')


# 发表评论和回复的表单类
class Comment(FlaskForm):
    content = TextAreaField(
        '评论内容',
        validators=[
            DataRequired('内容不能为空'),
            Length(min=5, max=100, message='博客内容在5~100字之间')
        ]
    )
    submit = SubmitField('发表')

blog/app/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request, jsonify
from app.forms import SendPosts, Comment  # 导入发表博客与评论回复表单类
from app.models import Posts, Category, Comment as Comments  # 导入博客模型类
from flask_login import login_required, current_user
from sqlalchemy import or_  # 导入或查询

posts = Blueprint('posts', __name__)


# 发表博客
@posts.route('/send_posts/', methods=['GET', 'POST'])
@login_required
def send_posts():
    form = SendPosts()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后在发表')
    elif form.validate_on_submit():
        # 保存发表博客的数据
        Posts(
            title=form.title.data,
            article=form.article.data,
            user=current_user,
            category_id=form.categories.data
        ).save()
        flash('博客发表成功')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form)



# 博客搜索
@posts.route('/search/', methods=['GET', 'POST'])
def search():
    try:
        page = request.args.get('page', 1, type=int)
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
        print(keyword)
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0并且所有人可见的博客  pid不为0 证明是评论和回复的内容  按照时间的降序显示
    pagination = Posts.query.filter(
        or_(
            Posts.title.ilike("%" + keyword + "%"),
            Posts.article.ilike("%" + keyword + "%")
        ),
        Posts.state == 0
    ).order_by(
        Posts.timestamp.desc()
    ).paginate(page, current_app.config['PAGE_NUM'])
    data = pagination.items  # 获取page页面的数据
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword)


# 博客详情
@posts.route('/posts_detail/')
def posts_detail():
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    pid = request.args.get("pid")
    page = request.args.get("page", 1, type=int)
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复 按照博客内容和回复在一起的排序顺序  过滤条件为博客的path宏包含博客id 的 这样就将博客的内容过滤了出去  只查询评论和回复的内容
    pagedata = Comments.query.filter(
        Comments.post_id == p.id
    ).order_by(Comments.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'])
    return render_template('posts/posts_detail.html', posts=p, form=form, comment=pagedata)


# 评论
@posts.route('/comment/', methods=["GET", "POST"])
@login_required
def comment():
    form = Comment()
    if form.validate_on_submit():
        page = request.form.get("page", 1, type=int)
        pid = request.form.get("pid", type=int)
        count = request.form.get("content")
        uid = current_user.id
        Comments(
            count=count,
            post_id=pid,
            user_id=uid
        ).save()
    return redirect(url_for("posts.posts_detail", pid=pid, page=page))


# 回复
@posts.route('/reply/', methods=['GET', 'POST'])
@login_required
def reply():
    page = request.form.get("page", 1, type=int)
    form = Comment()
    if form.validate_on_submit():
        pid = request.form.get('pid', type=int)
        rid = request.form.get('rid', type=int)
        count = request.form.get("content")
        uid = current_user.id
        Comments(
            count=count,
            post_id=pid,
            user_id=uid,
            replied_id=rid,
        ).save()
    return redirect(url_for('posts.posts_detail', pid=pid, page=page))


# 处理博客收藏与取消收藏的操作
@posts.route('/do_favorite/')
def do_favorite():
    try:
        # 获取ajax传递过来的pid
        pid = request.args.get('pid', type=int)
        # 判断是否收藏了
        if current_user.is_favorite(pid):
            # 调用取消收藏
            current_user.delete_favorite(pid)
        else:
            # 调用执行收藏
            current_user.add_favorite(pid)
        return jsonify({'res': 200})
    except:
        return jsonify({'res': 500})

blog/app/templates/posts/posts_detail.html
{% extends 'common/base.html' %}
{% block title %}
    博客详情...
{% endblock %}
{% block page_left %}
    <div class="row">
    <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12" style="padding: 0px 10px">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 article-detail">
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10 title">
                {{ posts.title }}
            </div>
            <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 favorite">
                <label class="collections">
                    <p onclick="doFavorite({{ posts.id }})" style="cursor:pointer;" id="collections">
                        {% if current_user.is_authenticated %}
                            {% if current_user.is_favorite(posts.id) %}
                                取消收藏
                            {% else %}
                                收藏本文
                            {% endif %}
                        {% else %}
                            收藏本文
                        {% endif %}
                    </p>
                </label>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 info">
                作者：{{ posts.user.username }}&nbsp;&nbsp;&nbsp;类别：{{ posts.categories.name }}&nbsp;&nbsp;&nbsp;
                发表于：{{ moment(posts.timestamp).format('YYYY-MM-DD H:m:s') }}&nbsp;&nbsp;&nbsp;
                阅读：{{ posts.visit }} 次&nbsp;&nbsp;&nbsp;
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 content" id="content">
                {{ posts.article|safe }}
            </div>
            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8" style="margin: 20px 0px; text-align: center;">
            </div>
            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 favorite" style="margin: 20px 0px;">
                {#                <label class="collections" onclick="doFavorite({{ posts.id }})" style="color: rgb(51, 122, 183);">#}
                {#                  #}
                {#                </label>#}
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 article-nav">
            <div>上一篇：
                <a href="" style="color: #000;">访谈:从电商专业转入Web前端，这位应届生的入职年薪20W！</a>
            </div>
            <div>下一篇：
                <a href="" style="color: #000;">资讯:PBET-7.0版课程详解之UI全链路设计！</a>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 article-comment" id="commenttop">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 add-comment">
                <div class="page-header" style="clear: both;"><h3>发表评论</h3></div>
                <form action="{{ url_for('posts.comment') }}" method="post">
                    {{ form.csrf_token }}
                    <input type="hidden" name="pid" value="{{ posts.id }}">
                    {{ form.content(class="form-control",style="height:200px;resize:none;",placeholder='请输入评论内容在5～100字之间',required='true',minlength=5,maxlength=100) }}
                    <br>
                    <button class="btn btn-success">发表评论</button>
                </form>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div id="commnetList">
                    {# 下面是评论内的显示和发表评论的代码#}
                    <div class="page-header" style="clear: both;"><h3>评论内容</h3></div>
                    {#评论和回复内容的显示#}
                    {% for message in comment.items %}
                        {% if not message.replied_id %}
                            <div class="media">
                                <div class="media">
                                    <div class="media-left media-middle">
                                        <a href="#">
                                            <img class="media-object"
                                                 src="{{ url_for('static',filename='upload/m_'+message.user.icon,_external=True) }}"
                                                 alt="..." width="50"
                                                 style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
                                        </a>
                                    </div>
                                    <div class="media-body">
                                        <h4 class="media-heading">
                                            {{ message.user.username }}
                                            <span style="float:right;font-size:14px;">{{ moment(message.timestamp).format('YYYY-MM-DD H:m:s') }} <button
                                                    class="btn btn-danger btn-xs"
                                                    onclick="replay({{ message.id }});">回复</button> </span></h4>
                                        <p>{{ message.count }}</p>
                                    </div>
                                </div>
                                {% for reply in message.replies %}
                                    <div class="media" style="margin-left: 20px">
                                        <div class="media-left media-middle">
                                            <a href="#">
                                                <img class="media-object"
                                                     src="{{ url_for('static',filename='upload/m_'+message.user.icon,_external=True) }}"
                                                     alt="..." width="50"
                                                     style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
                                            </a>
                                        </div>
                                        <div class="media-body">
                                            <h4 class="media-heading">
                                                {{ reply.user.username }} 回复了 {{ message.user.username }}
                                                <span style="float:right;font-size:14px;">{{ moment(reply.timestamp).format('YYYY-MM-DD H:m:s') }} <button
                                                        class="btn btn-danger btn-xs"
                                                        onclick="replay({{ reply.id }});">回复</button> </span></h4>
                                            <p>{{ reply.count }}</p>
                                        </div>
                                    </div>
                                    {% for r_reply in reply.replies %}
                                        <div class="media" style="margin-left: 20px">
                                            <div class="media-left media-middle">
                                                <a href="#">
                                                    <img class="media-object"
                                                         src="{{ url_for('static',filename='upload/m_'+message.user.icon,_external=True) }}"
                                                         alt="..." width="50"
                                                         style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
                                                </a>
                                            </div>
                                            <div class="media-body">
                                                <h4 class="media-heading">

                                                    {{ r_reply.user.username }} 回复了 {{ reply.user.username }}

                                                    <span style="float:right;font-size:14px;">{{ moment(message.timestamp).format('YYYY-MM-DD H:m:s') }} <button
                                                            class="btn btn-danger btn-xs"
                                                            onclick="replay({{ r_reply.id }});">回复</button> </span></h4>
                                                <p>{{ r_reply.count }}</p>
                                            </div>
                                        </div>
                                        <form action="{{ url_for('posts.reply') }}" method="post" class="replay"
                                              id="replay{{ r_reply.id|string }}">
                                            {{ form.csrf_token }}
                                            <input type="hidden" name="pid" value="{{ posts.id }}">
                                            <input type="hidden" name="rid" value="{{ r_reply.id }}">
                                            {{ form.content(class="form-control",style="height:100px;resize:none;",placeholder='请输入回复message内容在5～100字之间',required='true',minlength=5,maxlength=100) }}
                                            <br>
                                            <button class="btn btn-danger">发表回复</button>
                                        </form>
                                    {% endfor %}
                                    <form action="{{ url_for('posts.reply') }}" method="post" class="replay"
                                          id="replay{{ reply.id|string }}">
                                        {{ form.csrf_token }}
                                        <input type="hidden" name="pid" value="{{ posts.id }}">
                                        <input type="hidden" name="rid" value="{{ reply.id }}">
                                        {{ form.content(class="form-control",style="height:100px;resize:none;",placeholder='请输入回复replay内容在5～100字之间',required='true',minlength=5,maxlength=100) }}
                                        <br>
                                        <button class="btn btn-danger">发表回复</button>
                                    </form>
                                {% endfor %}

                            </div>
                            <form action="{{ url_for('posts.reply') }}" method="post" class="replay"
                                  id="replay{{ message.id|string }}">
                                {{ form.csrf_token }}
                                <input type="hidden" name="pid" value="{{ posts.id }}">
                                <input type="hidden" name="rid" value="{{ message.id }}">
                                {{ form.content(class="form-control",style="height:100px;resize:none;",placeholder='请输入回复message内容在5～100字之间',required='true',minlength=5,maxlength=100) }}
                                <br>
                                <button class="btn btn-danger">发表回复</button>
                            </form>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="margin-bottom: 20px;">
                    {#  分页的样式  #}
                    {% from 'common/page_macro.html' import page %}
                    {{ page(comment,'posts.posts_detail',pid=posts.id) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $(function () {
            $('.replay').hide();
        });

        //点击回复的js的函数
        function replay(pid) {
            $('.replay').hide();
            $('#replay' + pid).show()
        }

        //处理博客收藏功能的函数
        function doFavorite(pid) {
            //获取收藏的节点标签
            var collections = $('#collections');
            var html = collections.html();
            console.log(html);
            $.get({{ url_for('posts.do_favorite') }}, {'pid': pid}, function (data, status) {
                if (data.res == 200) {
                    if (html == '收藏本文') {
                        collections.html("取消收藏");
                    } else {
                        collections.html("收藏本文")
                    }
                } else if (window.confirm('您还没有登录？是否前去登录？')) {
                    window.location.href = '{{ url_for('user.login',_external=True) }}';
                }
            })
        }

        $(document).ready(function () {
            var fixedDiv = document.getElementById("fixedmenu");
            var H = 0;
            var Y = fixedDiv;
            while (Y) {
                H += Y.offsetTop;
                Y = Y.offsetParent;
            }

            window.onscroll = function () {
                var s = document.body.scrollTop || document.documentElement.scrollTop;
                s += 90;
                if (s > H) {
                    fixedDiv.style = "position:fixed; top:90px; margin-top:0px; width: 280px;";
                } else {
                    fixedDiv.style = "";
                }
            }
        });

        function doArticleSearch() {
            var keyword = $.trim($("#keyword").val());
            if (keyword.length < 2) {
                layer.msg("请输入至少两个关键字。", function () {
                    //关闭后的操作
                });
                $("#keyword").focus();
                return;
            }
            location.href = "/note/search/" + keyword;
        }
    </script>
{% endblock %}

blog/app/templates/posts/search_detail.html
{% extends 'common/base.html' %}
{% block title %}
    搜索...
{% endblock %}
{% block page_content %}
    {#  博客内容的展示  #}
    <div class="page-header"><h2>搜索包含<span style="color:red;">“{{ keyword }}”</span>博客的结果为...</h2></div>
    {% for p in posts %}
        <div class="media">
            <a href="{{ url_for('posts.posts_detail',pid=p.id,_external=True) }}"
               style="color:#000;text-decoration: none">
                <div class="media-left media-middle">
                    <img class="media-object" src="{{ url_for('static',filename='upload/s_'+p.user.icon) }}" alt="..."
                         width="100" style="border-radius: 5px;border-top:2px solid #ccc;border-right:2px solid #ccc;">
                </div>
                <div class="media-body">
                    <h4 class="media-heading" style="font-weight: bold;">{{ p.title }} <span
                            style="float:right;color:#ccc;font-size:14px;">{{ moment(p.timestamp).fromNow() }}</span>
                    </h4>
                    {{ p.article|striptags|showEllipsis }}
                </div>
            </a>
        </div>
    {% endfor %}
    {#  分页的样式  #}
    {% from 'common/page_macro.html' import page %}
    {{ page(pagination,'posts.search',keyword=keyword) }}
{% endblock %}
{% block page_right %}
{% endblock %}

blog/app/templates/posts/send_posts.html
{% extends 'common/base.html' %}
{% block title %}
    发表博客
{% endblock %}
{% from 'bootstrap/wtf.html' import quick_form %}
{% block scripts %}
    {{ super() }}
 <script src="//cdn.ckeditor.com/4.4.6/standard/ckeditor.js"></script>
{% endblock %}
{% block page_content %}
<h2 class="page-header">发表博客</h2>
    <form action="" method="post">
        {{ form.csrf_token }}
        {{ form.title.label() }}
        {{ form.title(class='form-control') }}
        {% for err in form.title.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br/>
        {{ form.categories.label() }}
        {{ form.categories(class='form-control') }}
        {% for err in form.categories.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br/>
        {{ form.article.label(style='font-size:16px;') }}
        {{ form.article(class="ckeditor") }}
        {% for err in form.article.errors %}
            <p style="color:red;">{{ err }}</p>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-success">发表</button>
    </form>
{% endblock %}
{% block page_right %}
{% endblock %}