blog/app/views/main.py
from flask import Blueprint, render_template, request, current_app
from werkzeug.security import generate_password_hash, check_password_hash
from app.models import Posts

main = Blueprint('main', __name__)

# @main.route("/test")
# def test_E():
#     from app.models.flask_sqlalchemy_test import User
#     data=User.query.all()
#     return str(data)

# 首页视图
@main.route('/')
def index():
    page = request.args.get('page', 1, type=int)
    if page == None:
        page = 1
    # 查询pid为0并且所有人可见的博客  pid不为0 证明是评论和回复的内容  按照时间的降序显示
    pagination = Posts.query.filter(
        Posts.state == 0
    ).order_by(
        Posts.timestamp.desc()
    ).paginate(page, current_app.config['PAGE_NUM'])
    data = pagination.items  # 获取page页面的数据
    return render_template('main/index.html', posts=data, pagination=pagination)

blog/app/views/owncenter.py
from flask import Blueprint, render_template, url_for, redirect, flash, request, current_app

from app.forms import UserInfo, CategoryForm  # 导入个人信息显示user模型类
from flask_login import current_user, login_required

from app.models import Posts, Category  # 导入博客的模型
from app.forms import SendPosts, Change_pwd_email, Upload  # 导入发表博客模型类 用于编辑博客  # 导入文件上传表单类
from app.extensions import db, file
import os
from PIL import Image

owncenter = Blueprint('owncenter', __name__)


# 查看与修改个人信息
@owncenter.route('/user_info/', methods=['GET', 'POST'])
@login_required
def user_info():
    form = UserInfo()
    if form.validate_on_submit():
        current_user.age = form.age.data
        current_user.sex = int(form.sex.data)
        current_user.save()
    # 表单设置默认值
    form.username.data = current_user.username
    form.age.data = current_user.age
    form.sex.data = str(int(current_user.sex))
    form.email.data = current_user.email
    form.lastLogin.data = current_user.lastLogin
    form.register.data = current_user.registerTime
    return render_template('owncenter/user_info.html', form=form)


# 修改密码
@owncenter.route("/cheage_password")
@login_required
def cheage_password():
    form = Change_pwd_email()
    if form.validate_on_submit():
        pass
    return render_template("owncenter/cheage_pwd_email.html", form=form)


# 修改邮箱
@owncenter.route("/cheage_email")
@login_required
def cheage_email():
    form = Change_pwd_email()
    if form.validate_on_submit():
        pass
    return render_template("owncenter/cheage_pwd_email.html", form=form)


# 博客管理
@owncenter.route('/posts_manager/', methods=['GET', 'POST'])
@login_required
def posts_manager():
    form = CategoryForm()

    # 查看当前用户发表的所有博客  pid为0证明是博客内容而不是评论和回复的内容 state=0是所有人可见  按照时间降序查询
    posts = current_user.posts.filter_by(state=0).order_by(Posts.timestamp.desc())
    return render_template('owncenter/posts_manager.html', posts=posts, form=form)


@owncenter.route('/add_category/', methods=['GET', 'POST'])
@login_required
def add_category():
    form = CategoryForm()
    if not form.validate_add_categories(form.add_categories):
        flash("添加失败,标签已经存在")
        return redirect(url_for("owncenter.posts_manager"))
    if request.method == "POST":
        Category(
            name=form.add_categories.data,
        ).save()
        flash("添加成功")
    else:
        flash("添加失败")
    return redirect(url_for("owncenter.posts_manager"))


@owncenter.route('/del_category/', methods=['GET', 'POST'])
@login_required
def del_category():
    gid = request.form.get("categories", type=int)
    g = Category.query.get_or_404(gid)
    if g:
        g.delete()
        flash("删除成功")
    else:
        flash("删除的标签不存在")
    return redirect(url_for("owncenter.posts_manager"))


# 博客删除
@owncenter.route('/del_posts/<int:pid>/')
@login_required
def del_posts(pid):
    # 查询博客
    p = Posts.query.get(pid)
    # 判断该博客是否存在
    if p:
        # 执行删除
        flash('删除成功')
        p.delete()  # 删除博客内容
    else:
        flash('您要删除的博客不存在')
    return redirect(url_for('owncenter.posts_manager'))


# 博客编辑
@owncenter.route('/edit_posts/<int:pid>/', methods=['GET', 'POST'])
def edit_posts(pid):
    form = SendPosts()  # 实例化表单
    p = Posts.query.get(pid)  # 根据博客id 查询
    if not p:
        flash('该博客不存在')
        return redirect(url_for('owncenter.posts_manager'))
    if form.validate_on_submit():
        p.title = form.title.data  # 进行数据的存储
        p.article = form.article.data
        p.save()
        flash('博客更新成功')
        return redirect(url_for('owncenter.posts_manager'))
    form.title.data = p.title
    form.article.data = p.article
    return render_template('owncenter/edit_posts.html', form=form)


#生成随机图片名称的函数
def new_name(shuffix,length=32):
    import string, random
    myStr = string.ascii_letters + '0123456789'
    newName = ''.join(random.choice(myStr) for i in range(length))
    return newName+"."+shuffix


# 图片缩放处理
def img_zoom(path,prefix="m_", width=200, height=200):
    # 打开文件
    img = Image.open(path)
    # 重新设计尺寸
    img.thumbnail((width, height))
    # 拆分传递进来的图片的路径 拆分进行前缀的拼接  /a/b.jpg  /a/s_b.jpg
    pathSplit = os.path.split(path)
    # 拼接好前缀 进行重新拼接成一个新的path
    path = os.path.join(pathSplit[0], prefix+pathSplit[1])
    # 保存缩放后的图片 保留原图片
    # 保存缩放
    img.save(path)


# 头像上传
@owncenter.route('/upload/', methods=['GET', 'POST'])
@login_required
def upload():
    form = Upload()
    # 验证数据
    if form.validate_on_submit():
        icon = request.files.get('icon')  # 获取上传对象
        suffix = icon.filename.split('.')[-1]  # 获取后缀
        newName = new_name(suffix)
        # 保存图片 以新名称
        file.save(icon, name=newName)
        delPath = current_app.config['UPLOADED_PHOTOS_DEST']
        # 删除之前上传过的图片
        if current_user.icon != 'default.png':  # 如果不等于 证明之前有上传过头像 否则就是没有上传过新头像
            os.remove(os.path.join(delPath, current_user.icon))
            os.remove(os.path.join(delPath, "m_"+current_user.icon))
        with db.auto_commit():
            current_user.icon = newName  # 更改当前对象的图片名称
            db.session.add(current_user)  # 更新到数据库中
        # 拼接图片路径
        path = os.path.join(delPath, newName)
        # 进行头像的缩放
        img_zoom(path)
    return render_template('owncenter/upload.html', form=form)


# 收藏管理
@owncenter.route('/my_favorite/')
@login_required
def my_favorite():
    # 查出当前用户的所有收藏的博客
    posts = current_user.favorites.all()
    return render_template('owncenter/my_favorite.html', posts=posts)


# 取消收藏
@owncenter.route('/del_favorites/<int:pid>/')
@login_required
def del_favorites(pid):
    # 判断是否收藏了
    if current_user.is_favorite(pid):
        # 调用取消收藏
        current_user.delete_favorite(pid)
    flash('取消收藏成功')
    return redirect(url_for('owncenter.my_favorite'))

blog/app/views/posts.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request, jsonify
from app.forms import SendPosts, Comment  # 导入发表博客与评论回复表单类
from app.models import Posts, Category, Comment as Comments  # 导入博客模型类
from flask_login import login_required, current_user
from sqlalchemy import or_  # 导入或查询

posts = Blueprint('posts', __name__)


# 发表博客
@posts.route('/send_posts/', methods=['GET', 'POST'])
@login_required
def send_posts():
    form = SendPosts()
    # 判断登录后在进行发表
    if not current_user.is_authenticated:
        flash('您还没有登录  请登录后在发表')
    elif form.validate_on_submit():
        # 保存发表博客的数据
        Posts(
            title=form.title.data,
            article=form.article.data,
            user=current_user,
            category_id=form.categories.data
        ).save()
        flash('博客发表成功')
        return redirect(url_for('main.index'))
    return render_template('posts/send_posts.html', form=form)



# 博客搜索
@posts.route('/search/', methods=['GET', 'POST'])
def search():
    try:
        page = request.args.get('page', 1, type=int)
    except:
        page = 1
    # 获取搜索的关键字
    if request.method == 'POST':
        keyword = request.form.get('keyword', '')
        print(keyword)
    else:
        keyword = request.args.get('keyword', '')
    # 查询pid为0并且所有人可见的博客  pid不为0 证明是评论和回复的内容  按照时间的降序显示
    pagination = Posts.query.filter(
        or_(
            Posts.title.ilike("%" + keyword + "%"),
            Posts.article.ilike("%" + keyword + "%")
        ),
        Posts.state == 0
    ).order_by(
        Posts.timestamp.desc()
    ).paginate(page, current_app.config['PAGE_NUM'])
    data = pagination.items  # 获取page页面的数据
    return render_template('posts/search_detail.html', pagination=pagination, posts=data, keyword=keyword)


# 博客详情
@posts.route('/posts_detail/')
def posts_detail():
    # 查询当前博客的内容 pid为博客的自增id 并不是博客模型字段的pid
    pid = request.args.get("pid")
    page = request.args.get("page", 1, type=int)
    p = Posts.query.get(pid)
    p.visit += 1  # 博客的访问量
    p.save()
    form = Comment()  # 发表评论和回复的表单类
    # 查询出博客的评论内容和回复 按照博客内容和回复在一起的排序顺序  过滤条件为博客的path宏包含博客id 的 这样就将博客的内容过滤了出去  只查询评论和回复的内容
    pagedata = Comments.query.filter(
        Comments.post_id == p.id
    ).order_by(Comments.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'])
    return render_template('posts/posts_detail.html', posts=p, form=form, comment=pagedata)


# 评论
@posts.route('/comment/', methods=["GET", "POST"])
@login_required
def comment():
    form = Comment()
    if form.validate_on_submit():
        page = request.form.get("page", 1, type=int)
        pid = request.form.get("pid", type=int)
        count = request.form.get("content")
        uid = current_user.id
        Comments(
            count=count,
            post_id=pid,
            user_id=uid
        ).save()
    return redirect(url_for("posts.posts_detail", pid=pid, page=page))


# 回复
@posts.route('/reply/', methods=['GET', 'POST'])
@login_required
def reply():
    page = request.form.get("page", 1, type=int)
    form = Comment()
    if form.validate_on_submit():
        pid = request.form.get('pid', type=int)
        rid = request.form.get('rid', type=int)
        count = request.form.get("content")
        uid = current_user.id
        Comments(
            count=count,
            post_id=pid,
            user_id=uid,
            replied_id=rid,
        ).save()
    return redirect(url_for('posts.posts_detail', pid=pid, page=page))


# 处理博客收藏与取消收藏的操作
@posts.route('/do_favorite/')
def do_favorite():
    try:
        # 获取ajax传递过来的pid
        pid = request.args.get('pid', type=int)
        # 判断是否收藏了
        if current_user.is_favorite(pid):
            # 调用取消收藏
            current_user.delete_favorite(pid)
        else:
            # 调用执行收藏
            current_user.add_favorite(pid)
        return jsonify({'res': 200})
    except:
        return jsonify({'res': 500})

blog/app/views/user.py
from flask import Blueprint,render_template,flash,redirect,url_for
from app.forms import Register,Login,AgainActive  # 导入表单注册类
from app.models import User  # 导入User模型类
from app.email import send_mail  # 导入发送邮件函数
from flask_login import login_required,logout_user,login_user,current_user
from datetime import datetime

user = Blueprint('user',__name__)
"""
# 注册步骤
1. 创建模型类
2. 加载flask-migrate扩展库（迁移）
3. 在视图函数中导入模型类
4. 验证（用户名、邮箱）是否存在
5. 获取模板前台传递过来的数据
6. 存储
7. 明文密码变成密文密码(加密存储)
8. 配置发送邮件扩展库和功能
9. 发送邮件
10. 消息闪现（注册成功 前去激活...）
"""
@user.route('/register/',methods=['GET','POST'])
def register():
    # 实例化注册表单类
    form = Register()
    if form.validate_on_submit():
        # 实例化存储注册表单数据
        u = User(
            username=form.username.data,
            password=form.userpass.data,
            email=form.email.data
        )
        u.save()
        # 调用获取生成token的方法
        token = u.generate_token()
        # 发送邮件激活
        send_mail('账户激活',form.email.data,username=form.username.data,token=token)
        flash('注册成功 前去邮箱进行激活')
        # 成功去登录
        return redirect(url_for('user.login'))
    return render_template('user/register.html',form=form)


# 进行账户激活的视图
@user.route('/active/<token>/')
def active(token):
    if User.check_token(token):
        flash('激活成功 请前去登录...')
        # 激活成功跳转到登录
        return redirect(url_for('user.login'))
    else:
        flash('激活失败  请重新进行账户激活操作...')
        return redirect(url_for(''))


# 再次激活的视图
@user.route('/again_active/',methods=['GET','POST'])
def again_active():
    form = AgainActive()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        # print(u)
        if not u:
            flash("请输入争取的用户名或密码...")
        elif not u.check_password(form.userpass.data):
            flash('请输入正确的用户名或密码')
        elif not u.confirm:
            # 调用获取生成token的方法
            token = u.generate_token()
            # 发送邮件激活
            send_mail('账户激活',u.email, username=form.username.data, token=token)
            flash('激活邮件发送成功 前去邮箱进行激活')
        else:
            flash('该账户已经激活 请前去登录...')
    return render_template('user/again_active.html',form=form)

"""
登录的步骤
1 接受表单传递过来的数据
2 查询用户名的对象
3 如果不存在则 提示
4 判断是否激活状态
5 判断密码(错误给出提示)
6 登录成功进行处理
7 登录失败 给出提示
"""
# 登录视图
@user.route('/login/',methods=['GET','POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('请输入正确的用户名或密码')
        elif not u.confirm:
            flash('您还没有激活 请前去激活账户')
            return redirect(url_for('user.again_active'))
        elif not u.check_password(form.userpass.data):
            flash('请输入正确的用户名或密码')
        else:
            flash('登录成功')
            # 修改登录时间
            u.lastLogin = datetime.now()
            u.save()
            login_user(u,remember=form.remember.data) # 使用第三方扩展库处理登录状态的维持
            return redirect(url_for('main.index'))

    return render_template('user/login.html',form=form)



# 退出登录
@user.route('/logout/')
def logout():
    logout_user()
    flash('退出成功！')
    return redirect(url_for('main.index'))

blog/app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% block head %}
    {{ super() }}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="http://example.com/myicon.png">
{% endblock %}
{% block title %}

{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet" type="text/css" href="{{ url_for("static",filename="css/bootstrap.css") }}">
    <link rel="stylesheet" href="{{ url_for("static",filename="css/bossqiang.css") }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for("static",filename="css/layer.css") }}" id="layuicss-layer">
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                {#                <a class="navbar-brand" href="#">#}
                {#                    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>#}
                {#                </a>#}
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index',_external=True) }}">首页 <span class="sr-only">(current)</span></a>
                    </li>

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a>欢迎：{{ current_user.username }}</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="{{ url_for('owncenter.user_info',_external=True) }}" target="_blank">查看与修改个人信息</a>
                                </li>
                                <li><a href="{{ url_for('owncenter.upload') }}" target="_blank">上传头像</a></li>
                                <li><a href="{{ url_for('owncenter.cheage_password') }}" target="_blank">修改密码</a></li>
                                <li><a href="{{ url_for('owncenter.cheage_email') }}" target="_blank">修改邮箱</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('owncenter.posts_manager') }}" target="_blank">博客管理</a></li>
                                <li><a href="{{ url_for('owncenter.my_favorite') }}" target="_blank">收藏管理</a></li>
                                <li><a href="{{ url_for('posts.send_posts',_external=True) }}">发表博客</a></li>
                            </ul>
                        </li>
                        <li><a href="{{ url_for('user.logout',_external=True) }}">退出登录</a></li>
                    {% else %}
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                        <li><a href="{{ url_for('user.register',_external=True) }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
{% endblock %}
{% block content %}
{#    <div class="content">#}
        <div class="container">
            {#    配置消息的闪现    #}
            {% for msg in get_flashed_messages() %}
                <div class="alert alert-warning alert-dismissible" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <strong>{{ msg }}</strong>
                </div>
            {% endfor %}
        {% block page_content %}

        {% endblock %}
        <div class="row">
            {% block page_left %}
                <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12 ">


                </div>
            {% endblock %}

            {% block page_right %}
                <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" style="padding: 0px 10px;">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 search-bar form-group">
                <form action="{{ url_for('posts.search',_external=True) }}" method="POST">
                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
                    <input type="text" class="form-control" placeholder="请输入关键字" name="keyword">
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4" style="text-align:right;line-height:30px;">
                    <button type="submit" class="btn btn-primary">搜索</button>
                </div>
                </form>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 left-side">
                <div class="tip">最新文章</div>
                <ul>
                    <li><a href="">1. 资讯: 妈呀！他们工资好高啊！...</a></li>

                </ul>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 left-side">
                <div class="tip">最多访问</div>
                <ul>
                    <li><a href="">1. 访谈: 西安校区17期软件测试...</a></li>

                </ul>
            </div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 hidden-sm hidden-xs left-side" id="fixedmenu">
                <div class="tip">热门推荐</div>
                <ul>
                    <li><a href="">1. 资讯: IT行业激荡30年-&gt;改变...</a></li>

                </ul>
            </div>
        </div>
            {% endblock %}

        </div>
        </div>
{#    </div>#}
{% endblock %}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{#    <script src="{{ url_for("static",filename="js/jquery-3.5.1.min.js") }}"></script>#}
{#    <script src="{{ url_for("static",filename="js/bootstrap.js") }}"></script>#}
    <script>
         $(document).ready(function () {
            var fixedDiv = document.getElementById("fixedmenu");
            var H = 0;
            var Y = fixedDiv;
            while (Y) {
                H += Y.offsetTop;
                Y = Y.offsetParent;
            }

            window.onscroll = function () {
                var s = document.body.scrollTop || document.documentElement.scrollTop;
                s += 90;
                if (s > H) {
                    fixedDiv.style = "position:fixed; top:90px; margin-top:0px; width: 280px;";
                } else {
                    fixedDiv.style = "";
                }
            }
        });
    </script>
{% endblock %}

blog/app/templates/common/page_macro.html
{% macro page(pagination,endPoint) %}
            <ul class="pagination">
            <li><a href="{{ url_for(endPoint,page=1) }}">首页</a></li>
                <li {% if not pagination.has_prev %}class="disabled"{% endif %}>
                    <a {% if pagination.has_prev %}href="{{ url_for(endPoint,page=pagination.prev_num,**kwargs) }}"{% endif %} aria-label="Previous">
                        <span aria-hidden="true">上一页</span>
                    </a>
                </li>
                {% for p in pagination.iter_pages() %}
                    <li {% if p==pagination.page %}class="active"{% endif %}><a href="{{ url_for(endPoint,page=p,**kwargs) }}">{{ p }}</a></li>
                {% endfor %}
                <li {% if not pagination.has_next %}class="disabled"{% endif %}>
                    <a {% if pagination.has_next %}href="{{ url_for(endPoint,page=pagination.next_num,**kwargs) }}"{% endif %} aria-label="Next">
                        <span aria-hidden="true">下一页</span>
                    </a>
                </li>
            <li><a href="{{ url_for(endPoint,page=pagination.pages) }}">尾页</a></li>

            </ul>
{% endmacro %}